name: GEAR_data_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py310h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=21.1.8=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h99b78c6_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py310haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.15=hb885b13_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py310h5a8c52c_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py310haa24f5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - docstring-parser==0.17.0
      - et-xmlfile==2.0.0
      - fonttools==4.61.1
      - idna==3.11
      - imageio==2.37.2
      - ipywidgets==8.1.8
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - llvmlite==0.46.0
      - magicgui==0.10.1
      - matplotlib==3.10.8
      - networkx==3.4.2
      - numba==0.63.1
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - pandas==2.3.3
      - pillow==12.0.0
      - psygnal==0.15.0
      - pyconify==0.2.1
      - pyparsing==3.3.1
      - pytz==2025.2
      - qtpy==2.4.3
      - requests==2.32.5
      - scikit-image==0.25.2
      - scipy==1.15.3
      - skan==0.12.2
      - superqt==0.7.7
      - tifffile==2025.5.10
      - toolz==1.1.0
      - tqdm==4.67.1
      - tzdata==2025.3
      - urllib3==2.6.2
      - widgetsnbextension==4.0.15
